---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-16.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[linus-spigot-server::default]
    attributes:
