cookbook_path   ["/home/ubuntu/chef-repo/cookbooks","home/ubuntu/chef-repo/cookbooks/linus-spigot-server/berks-cookbooks"]
#role_path '/home/ubuntu/chef-repo/roles'
#data_bag_path  '/home/ubuntu/chef-repo/data_bags'
#environment_path '/home/ubuntu/chef-repo/environments'
#encrypted_data_bag_secret '/etc/chef'
#environment 'production'
#local_mode 'true'
#node_name 'node'
#node_path '/home/ubuntu/chef-repo/nodes'
log_level :info
